export const WEDDING_THEMES = [
  { value: "classic", label: "Classic & Elegant" },
  { value: "rustic", label: "Rustic & Country" },
  { value: "vintage", label: "Vintage & Retro" },
  { value: "modern", label: "Modern & Minimalist" },
  { value: "bohemian", label: "Bohemian & Boho" },
  { value: "garden", label: "Garden & Outdoor" },
  { value: "beach", label: "Beach & Coastal" },
  { value: "industrial", label: "Industrial & Urban" },
  { value: "romantic", label: "Romantic & Soft" },
  { value: "tropical", label: "Tropical & Exotic" },
  { value: "winter", label: "Winter Wonderland" },
  { value: "spring", label: "Spring & Floral" },
  { value: "summer", label: "Summer & Bright" },
  { value: "autumn", label: "Autumn & Warm" },
  { value: "mediterranean", label: "Mediterranean" },
  { value: "asian", label: "Asian & Oriental" },
  { value: "french", label: "French Countryside" },
  { value: "tuscany", label: "Tuscan & Italian" },
  { value: "nordic", label: "Nordic & Scandinavian" },
  { value: "art-deco", label: "Art Deco & Glamorous" },
  { value: "barn", label: "Barn & Farmhouse" },
  { value: "winery", label: "Winery & Vineyard" },
  { value: "castle", label: "Castle & Fairytale" },
  { value: "destination", label: "Destination Wedding" },
  { value: "cultural", label: "Cultural & Traditional" },
  { value: "eclectic", label: "Eclectic & Unique" },
  { value: "luxury", label: "Luxury & Opulent" },
  { value: "intimate", label: "Intimate & Cozy" },
  { value: "grand", label: "Grand & Extravagant" },
  { value: "casual", label: "Casual & Relaxed" },
];

